"""created is_deceased

Revision ID: 1aabfbda1eab
Revises: 422ce43dda4a
Create Date: 2023-10-31 15:44:14.427813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aabfbda1eab'
down_revision: Union[str, None] = '422ce43dda4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('is_deceased', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'is_deceased')
    # ### end Alembic commands ###
